[workspace]

[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = "0.11.1"

[dependencies]
common = { path = "../../common" }
risc0-zkvm-guest = "0.11.1"

[profile.release]
lto = true
opt-level = "z"